word_list = [
    'broccoli',
    'carrot',
    'spinach',
    'sweet potatoes',
    'blueberries',
    'raspberries',
    'blackberries',
    'cherries',
    'apple',
    'banana',
    'orange',
    'kiwi',
    'dragonfruit',
    'pear',
    'brussel sprouts',
    'radish',
    'beetroot',
    'plum',
    'strawberries',
    'melon',
    'eggplant',
    'french beans',
    'beansprout',
    'pumpkin',
    'cabbage'
]
